--- #YAML:1.0
name:               Object-Import
version:            1.001
abstract:           import methods of an object as functions to a package
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    File::Temp:    0
    IO::Handle:    0
    Math::BigInt:  1.59
    MRO::Compat:   0
    Scalar::Util:  0
    strict:        0
    Test::More:    0.47
    warnings:      0
requires:
    IO::Handle:    0
    MRO::Compat:   0
    perl:          5.006
    Scalar::Util:  0
    strict:        0
    warnings:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
