---
abstract: 'import methods of an object as functions to a package'
author:
  - unknown
build_requires:
  File::Temp: 0
  IO::Handle: 0
  MRO::Compat: 0
  Math::BigInt: 1.59
  Scalar::Util: 0
  Test::More: 0.47
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Object-Import
no_index:
  directory:
    - t
    - inc
requires:
  IO::Handle: 0
  MRO::Compat: 0
  Scalar::Util: 0
  perl: 5.008
  strict: 0
  warnings: 0
version: 1.004
